# Train/val/test set as 1) dir:path/to/imgs 2)file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: '/teamspace/studios/this_studio' # dataset root dir
train: images/train # train images (relative to 'path')
val: images/train #val images (relative to 'path')
# Classes
names:
  0: TomatoeBacterialSpot
  1: TomatoeEarlyblight
  2: TomatoeHealthy
  3: TomatoeLateBlight
  4: TomatoeLeafMold
  5: TomatoeSeptoriaLeafSpot
  6: TomatoeSpiderMites
  7: TomatoeTargetSpot
  8: TomatoeMosaicVirus
  9: TomatoeYellowLeafCurlVirus