# Train/val/test set as 1) dir:path/to/imgs 2)file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: 'C:\Users\ziads\Desktop\AppleYolo' # dataset root dir
train: images/train # train images (relative to 'path')
val: images/train #val images (relative to 'path')
# Classes
names:
  0: AppleScab
  1: AppleBlackRot
  2: AppleCedarRust
  3: AppleHealthy